image: docker:latest
services:
  - docker:dind

cache:
  paths:
   - .m2/repository

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - test
  - build
  - package
  - deploy

maven-test:
  image: maven:3-jdk-11
  stage: test
  script:
    - mvn verify --file root/pom.xml
  artifacts:
    reports:
      junit:
        - root/server/target/surefire-reports/TEST-*.xml
        - root/server/target/failsafe-reports/TEST-*.xml
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: 
   - mvn package -B -Dmaven.test.skip=true --file root/pom.xml
  artifacts:
    paths:
      - root/server/target/*.jar
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

docker-build:
  stage: package
  script:
   - docker build -t registry.gitlab.com/toofun-group/kaseb-server .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
   - docker push registry.gitlab.com/toofun-group/kaseb-server
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

arvan-deploy:
  image: mormoroth/arvancli
  stage: deploy
  script:
  - echo '$ARVAN_CLI_TOKEN\n' | arvan login
  - arvan paas status
#  - gcloud auth activate-service-account --key-file key.json
#  - gcloud config set compute/zone europe-west1-c
#  - gcloud config set project actuator-sample
#  - gcloud config set container/use_client_certificate True
#  - gcloud container clusters get-credentials actuator-sample
#  - kubectl delete secret registry.gitlab.com
#  - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=marcolenzo --docker-password=$REGISTRY_PASSWD --docker-email=lenzo.marco@gmail.com
#  - kubectl apply -f deployment.yml
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'
  tags:
    - arvan
