server:
  port: 1212
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/kaseb"
    username: "kaseb"
    password: "kaseb"
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitoring"

monitoring:
  user: kaseb
  password: HW9Z954sefKxpWDDtcxEaZF2MEtQAccBW2Sb4B4ng22JThDUs9rSDccyRXP3
