server:
  port: 1212
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/kaseb"
    username: "kaseb"
    password: "kaseb"
  liquibase:
    enabled: true
    dropFirst: false
    changeLog: "classpath:/db/changelog/db.changelog-master.xml"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitoring"
logging:
  level:
    root: info

monitoring:
  user: kaseb
  password: HW9Z954sefKxpWDDtcxEaZF2MEtQAccBW2Sb4B4ng22JThDUs9rSDccyRXP3
